-- Product Service Database (Production)
DROP DATABASE IF EXISTS product_db;
CREATE DATABASE product_db;
USE product_db;

CREATE TABLE categories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  description TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  category_id INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  price DECIMAL(12,2) NOT NULL,
  cost DECIMAL(12,2),
  stock INT NOT NULL DEFAULT 0,
  min_stock INT DEFAULT 10,
  sku VARCHAR(100) UNIQUE,
  image_url VARCHAR(255),
  status VARCHAR(50) DEFAULT 'active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE
);

CREATE TABLE product_reviews (
  id INT AUTO_INCREMENT PRIMARY KEY,
  product_id INT NOT NULL,
  user_id INT NOT NULL,
  rating INT CHECK (rating >= 1 AND rating <= 5),
  comment TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

CREATE TABLE product_inventory (
  id INT AUTO_INCREMENT PRIMARY KEY,
  product_id INT NOT NULL,
  quantity_change INT NOT NULL,
  transaction_type VARCHAR(50) NOT NULL,
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

INSERT INTO categories (name, description) VALUES
('Electronics', 'Electronic devices and gadgets'),
('Clothing', 'Fashion and apparel items'),
('Home & Garden', 'Household items and garden products'),
('Sports & Outdoors', 'Sports equipment and outdoor gear'),
('Books', 'Digital and physical books'),
('Toys & Games', 'Toys, games, and entertainment'),
('Beauty & Personal Care', 'Cosmetics and personal care items'),
('Furniture', 'Home furniture and decor'),
('Food & Beverages', 'Gourmet food and beverages'),
('Office Supplies', 'Office equipment and supplies');

INSERT INTO products (category_id, name, description, price, cost, stock, sku, status) VALUES
(1, 'Wireless Headphones Pro', 'Premium wireless headphones with noise cancellation', 129.99, 45.00, 150, 'ELEC001', 'active'),
(2, 'Classic Cotton T-Shirt', 'Comfortable everyday cotton t-shirt in multiple colors', 19.99, 5.50, 200, 'CLTH001', 'active'),
(3, 'Indoor Plant Collection', 'Beautiful set of 5 indoor plants with pots', 49.99, 18.00, 120, 'HOME001', 'active'),
(4, 'Professional Yoga Mat', 'Non-slip yoga mat with carrying strap', 39.99, 12.00, 100, 'SPRT001', 'active'),
(5, 'The Art of Programming', 'Comprehensive guide to modern programming', 59.99, 20.00, 180, 'BOOK001', 'active'),
(6, 'Educational Board Game Set', 'Fun and educational games for families', 34.99, 10.00, 160, 'TOYS001', 'active'),
(7, 'Organic Skincare Bundle', 'Natural skincare products set', 79.99, 25.00, 140, 'BEAU001', 'active'),
(8, 'Wooden Coffee Table', 'Modern wooden coffee table for living room', 199.99, 75.00, 50, 'FURN001', 'active'),
(9, 'Gourmet Coffee Beans', 'Premium single-origin coffee beans', 24.99, 7.00, 170, 'FOOD001', 'active'),
(10, 'Desk Organizer Kit', 'Complete desk organization system', 44.99, 14.00, 110, 'OFFC001', 'active'),
(1, 'Portable SSD 1TB', 'Fast and reliable external solid state drive', 99.99, 35.00, 145, 'ELEC002', 'active'),
(2, 'Denim Jeans', 'Classic blue denim jeans', 54.99, 15.00, 195, 'CLTH002', 'active'),
(3, 'Smart Watering System', 'Automatic watering system for plants', 79.99, 25.00, 115, 'HOME002', 'active'),
(4, 'Running Shoes Professional', 'High-performance running shoes', 119.99, 40.00, 95, 'SPRT002', 'active'),
(5, 'Data Science Handbook', 'Advanced data science techniques', 74.99, 25.00, 175, 'BOOK002', 'active'),
(6, 'STEM Building Blocks', 'Creative STEM learning kit', 44.99, 13.00, 155, 'TOYS002', 'active'),
(7, 'Luxury Bath Set', 'Spa-quality bath products', 89.99, 28.00, 135, 'BEAU002', 'active'),
(8, 'Bookshelf 5-Tier', 'Solid wood bookshelf storage', 179.99, 65.00, 60, 'FURN002', 'active'),
(9, 'Artisan Chocolate Box', 'Premium assorted chocolate collection', 34.99, 10.00, 125, 'FOOD002', 'active'),
(10, 'Ergonomic Chair Cushion', 'Back support cushion for office chairs', 35.99, 11.00, 105, 'OFFC002', 'active'),
(1, 'USB-C Hub 7-in-1', 'Multi-port USB-C hub for productivity', 69.99, 22.00, 140, 'ELEC003', 'active'),
(2, 'Sweater Hoodie Cozy', 'Soft and warm hoodie for cold weather', 59.99, 18.00, 190, 'CLTH003', 'active'),
(3, 'Raised Garden Bed', 'Wooden raised garden bed kit', 89.99, 30.00, 110, 'HOME003', 'active'),
(4, 'Tennis Racket Carbon', 'Professional grade tennis racket', 149.99, 50.00, 90, 'SPRT003', 'active'),
(5, 'Web Development Mastery', 'Complete web development course book', 69.99, 23.00, 170, 'BOOK003', 'active'),
(6, 'Robot Assembly Kit', 'Build your own robot educational toy', 79.99, 24.00, 150, 'TOYS003', 'active'),
(7, 'Anti-Aging Serum', 'Premium anti-aging skincare serum', 99.99, 32.00, 130, 'BEAU003', 'active'),
(8, 'Wall Mount TV Stand', 'Adjustable wall-mounted TV stand', 149.99, 55.00, 45, 'FURN003', 'active'),
(9, 'Organic Tea Selection', 'Assorted organic tea collection', 29.99, 9.00, 160, 'FOOD003', 'active'),
(10, 'Filing Cabinet 4-Drawer', 'Metal filing cabinet for office', 124.99, 42.00, 75, 'OFFC003', 'active'),
(1, '4K Wireless Monitor', 'Ultra HD wireless display monitor', 399.99, 140.00, 80, 'ELEC004', 'active'),
(1, 'Gaming Mouse RGB', 'High precision gaming mouse with RGB lighting', 79.99, 25.00, 200, 'ELEC005', 'active'),
(2, 'Leather Jacket', 'Premium genuine leather jacket', 299.99, 100.00, 85, 'CLTH004', 'active'),
(2, 'Casual Sneakers', 'Comfortable casual canvas sneakers', 89.99, 28.00, 160, 'CLTH005', 'active'),
(3, 'Outdoor Furniture Set', 'Complete outdoor patio furniture set', 599.99, 200.00, 35, 'HOME004', 'active'),
(3, 'Garden Tool Kit', 'Professional garden tools set with bag', 129.99, 40.00, 95, 'HOME005', 'active'),
(4, 'Camping Tent 4-Person', 'Waterproof 4-person camping tent', 249.99, 80.00, 70, 'SPRT004', 'active'),
(4, 'Mountain Bike', 'All-terrain mountain bike with suspension', 799.99, 280.00, 40, 'SPRT005', 'active'),
(5, 'Machine Learning Guide', 'Practical machine learning techniques', 89.99, 30.00, 165, 'BOOK004', 'active'),
(5, 'Cloud Architecture Handbook', 'Cloud computing architecture best practices', 79.99, 27.00, 155, 'BOOK005', 'active'),
(6, 'Drone for Beginners', 'Easy-to-use beginner drone with camera', 199.99, 65.00, 110, 'TOYS004', 'active'),
(6, '3D Puzzle Collection', 'Advanced 3D brain teaser puzzles set', 44.99, 14.00, 140, 'TOYS005', 'active'),
(7, 'Facial Clay Mask', 'Purifying facial clay mask treatment', 34.99, 11.00, 175, 'BEAU004', 'active'),
(7, 'Premium Shampoo Set', 'Luxury shampoo and conditioner set', 59.99, 18.00, 145, 'BEAU005', 'active'),
(8, 'Office Desk Standing', 'Adjustable electric standing desk', 449.99, 160.00, 55, 'FURN004', 'active'),
(8, 'Dining Table Set', 'Modern dining table with 6 chairs', 699.99, 240.00, 30, 'FURN005', 'active'),
(9, 'Premium Honey Collection', 'Assorted premium raw honey varieties', 44.99, 14.00, 120, 'FOOD004', 'active'),
(9, 'Specialty Spice Pack', 'Gourmet specialty spices collection', 39.99, 12.00, 130, 'FOOD005', 'active'),
(10, 'Ergonomic Keyboard', 'Ergonomic wireless mechanical keyboard', 129.99, 42.00, 125, 'OFFC004', 'active'),
(10, 'Monitor Stand Adjustable', 'Height adjustable monitor stand with storage', 79.99, 25.00, 150, 'OFFC005', 'active');

INSERT INTO product_reviews (product_id, user_id, rating, comment) VALUES
(1, 1, 5, 'Excellent sound quality! Worth every penny'),
(1, 2, 4, 'Great headphones, very comfortable to wear'),
(2, 3, 5, 'Perfect fit and great quality fabric'),
(3, 4, 4, 'Plants arrived healthy, instructions were clear'),
(4, 5, 5, 'Amazing yoga mat, very durable and non-slip'),
(5, 6, 3, 'Good book but some chapters could be more detailed'),
(6, 7, 5, 'Family loved this game set, highly recommend'),
(7, 8, 4, 'Very effective skincare products'),
(8, 9, 5, 'Beautiful design and sturdy construction'),
(9, 10, 4, 'Excellent coffee, best quality beans'),
(10, 1, 5, 'Desk organizer is so useful and well-designed'),
(11, 2, 4, 'Fast storage drive, great value'),
(12, 3, 5, 'Perfect jeans, very comfortable'),
(13, 4, 4, 'Smart watering system works great'),
(14, 5, 5, 'Professional running shoes, excellent support'),
(15, 6, 4, 'Comprehensive data science resource'),
(16, 7, 5, 'Kids love this STEM kit, very educational'),
(17, 8, 4, 'Luxury bath products smell amazing'),
(18, 9, 5, 'Bookshelf is beautiful and spacious'),
(19, 10, 4, 'Delicious chocolate, premium quality'),
(20, 1, 5, 'Back support cushion is very helpful'),
(21, 2, 4, 'USB-C hub works perfectly with my laptop'),
(22, 3, 5, 'Cozy hoodie, exactly what I needed'),
(23, 4, 4, 'Raised garden bed is easy to assemble'),
(24, 5, 5, 'Tennis racket has great balance'),
(25, 6, 3, 'Good book but a bit technical for beginners'),
(26, 7, 5, 'Robot kit is engaging and fun'),
(27, 8, 4, 'Anti-aging serum shows real results'),
(28, 9, 5, 'TV stand is sturdy and well-made'),
(29, 10, 4, 'Organic tea tastes wonderful'),
(30, 1, 5, 'Filing cabinet is perfect for organizing'),
(1, 3, 4, 'Good sound but slightly pricey'),
(2, 4, 4, 'Quality material, good value'),
(3, 5, 5, 'Plants are thriving, great care'),
(4, 6, 4, 'Good yoga mat, very supportive'),
(5, 7, 5, 'Essential reading for programmers'),
(6, 8, 5, 'Family bonding time with games'),
(7, 9, 4, 'Skincare products are gentle'),
(8, 10, 5, 'Coffee table enhances room decor'),
(9, 1, 4, 'Coffee beans are fresh and flavorful'),
(31, 2, 5, 'Amazing 4K monitor, crystal clear display'),
(31, 3, 4, 'Excellent color accuracy and brightness'),
(32, 4, 5, 'Gaming mouse is very responsive and precise'),
(32, 5, 4, 'Comfortable grip, love the RGB lighting'),
(33, 6, 5, 'Leather jacket is high quality and stylish'),
(33, 7, 4, 'Perfect fit, excellent craftsmanship'),
(34, 8, 5, 'Casual sneakers are very comfortable'),
(34, 9, 4, 'Great design and durable material'),
(35, 10, 5, 'Outdoor furniture set is beautiful and sturdy'),
(35, 1, 4, 'Perfect for backyard entertaining'),
(36, 2, 5, 'Garden tool kit has everything needed'),
(36, 3, 4, 'Well-organized set with quality tools'),
(37, 4, 5, 'Camping tent is waterproof and spacious'),
(37, 5, 4, 'Easy to set up, great value'),
(38, 6, 5, 'Mountain bike performs excellently on trails'),
(38, 7, 4, 'Smooth ride, excellent suspension'),
(39, 8, 5, 'Machine Learning Guide is comprehensive'),
(39, 9, 4, 'Practical examples and clear explanations'),
(40, 10, 5, 'Cloud Architecture book is highly informative'),
(40, 1, 4, 'Best practices clearly explained'),
(41, 2, 5, 'Drone is easy for beginners, great quality'),
(41, 3, 4, 'Camera quality is impressive'),
(42, 4, 5, '3D puzzles are challenging and fun'),
(42, 5, 4, 'Great brain teaser collection'),
(43, 6, 5, 'Facial mask left skin feeling refreshed'),
(43, 7, 4, 'Natural ingredients, very effective'),
(44, 8, 5, 'Premium shampoo set smells amazing'),
(44, 9, 4, 'Hair feels silky and healthy'),
(45, 10, 5, 'Standing desk is solidly built and ergonomic'),
(45, 1, 4, 'Great for reducing back pain'),
(46, 2, 5, 'Dining table set is beautiful and spacious'),
(46, 3, 4, 'Excellent construction quality'),
(47, 4, 5, 'Premium honey is pure and delicious'),
(47, 5, 4, 'Great taste, authentic quality'),
(48, 6, 5, 'Specialty spices add amazing flavor'),
(48, 7, 4, 'Fresh and aromatic spice collection'),
(49, 8, 5, 'Ergonomic keyboard reduces wrist strain'),
(49, 9, 4, 'Mechanical switches feel great to type'),
(50, 10, 5, 'Monitor stand improves desk organization'),
(50, 1, 4, 'Adjustable height works perfectly');

