-- User Service Database (Production)
DROP DATABASE IF EXISTS user_db;
CREATE DATABASE user_db;
USE user_db;

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  phone VARCHAR(20),
  address VARCHAR(255),
  city VARCHAR(100),
  country VARCHAR(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE user_profiles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL UNIQUE,
  bio TEXT,
  avatar_url VARCHAR(255),
  status VARCHAR(50) DEFAULT 'active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

INSERT INTO users (name, email, phone, address, city, country) VALUES
(1, 'John Doe', 'john.doe@example.com', '+1234567890', '123 Main Street', 'New York', 'USA'),
(2, 'Jane Smith', 'jane.smith@example.com', '+1987654321', '456 Oak Avenue', 'Los Angeles', 'USA'),
(3, 'Michael Johnson', 'michael.johnson@example.com', '+1555123456', '789 Pine Road', 'Chicago', 'USA'),
(4, 'Sarah Williams', 'sarah.williams@example.com', '+1555987654', '321 Elm Street', 'Houston', 'USA'),
(5, 'David Brown', 'david.brown@example.com', '+1555456789', '654 Maple Drive', 'Phoenix', 'USA'),
(6, 'Emily Davis', 'emily.davis@example.com', '+1555654321', '987 Birch Lane', 'Philadelphia', 'USA'),
(7, 'Robert Wilson', 'robert.wilson@example.com', '+1555789012', '147 Cedar Court', 'San Antonio', 'USA'),
(8, 'Jessica Martinez', 'jessica.martinez@example.com', '+1555012345', '258 Spruce Street', 'San Diego', 'USA'),
(9, 'James Anderson', 'james.anderson@example.com', '+1555345678', '369 Walnut Avenue', 'Dallas', 'USA'),
(10, 'Patricia Taylor', 'patricia.taylor@example.com', '+1555678901', '741 Hickory Drive', 'San Jose', 'USA'),
(11, 'Christopher Lee', 'christopher.lee@example.com', '+1555901234', '852 Ash Street', 'Austin', 'USA'),
(12, 'Linda Harris', 'linda.harris@example.com', '+1555234567', '963 Juniper Lane', 'Jacksonville', 'USA'),
(13, 'Daniel Clark', 'daniel.clark@example.com', '+1555567890', '147 Magnolia Drive', 'Fort Worth', 'USA'),
(14, 'Karen Lewis', 'karen.lewis@example.com', '+1555890123', '258 Poplar Street', 'Columbus', 'USA'),
(15, 'Matthew Walker', 'matthew.walker@example.com', '+1555123789', '369 Sycamore Avenue', 'Charlotte', 'USA'),
(16, 'Nancy Hall', 'nancy.hall@example.com', '+1555456012', '741 Laurel Court', 'San Francisco', 'USA'),
(17, 'Mark Young', 'mark.young@example.com', '+1555789345', '852 Oak Terrace', 'Indianapolis', 'USA'),
(18, 'Sandra Hernandez', 'sandra.hernandez@example.com', '+1555012678', '963 Elm Avenue', 'Austin', 'USA'),
(19, 'Donald King', 'donald.king@example.com', '+1555345901', '147 Pine Street', 'Seattle', 'USA'),
(20, 'Ashley Wright', 'ashley.wright@example.com', '+1555678234', '258 Maple Lane', 'Denver', 'USA'),
(21, 'Steven Lopez', 'steven.lopez@example.com', '+1555901567', '369 Cedar Drive', 'Boston', 'USA'),
(22, 'Dorothy Hill', 'dorothy.hill@example.com', '+1555234890', '741 Birch Court', 'El Paso', 'USA'),
(23, 'Paul Scott', 'paul.scott@example.com', '+1555567123', '852 Spruce Street', 'Memphis', 'USA'),
(24, 'Barbara Green', 'barbara.green@example.com', '+1555890456', '963 Walnut Avenue', 'Baltimore', 'USA'),
(25, 'Andrew Adams', 'andrew.adams@example.com', '+1555123456', '147 Hickory Drive', 'Boston', 'USA'),
(26, 'Donna Nelson', 'donna.nelson@example.com', '+1555456789', '258 Chestnut Lane', 'Milwaukee', 'USA'),
(27, 'Joshua Carter', 'joshua.carter@example.com', '+1555789012', '369 Dogwood Street', 'New Orleans', 'USA'),
(28, 'Pamela Mitchell', 'pamela.mitchell@example.com', '+1555012345', '741 Redbud Avenue', 'Las Vegas', 'USA'),
(29, 'Kenneth Roberts', 'kenneth.roberts@example.com', '+1555345678', '852 Ash Drive', 'Louisville', 'USA'),
(30, 'Kathleen Phillips', 'kathleen.phillips@example.com', '+1555678901', '963 Alder Lane', 'Portland', 'USA');
INSERT INTO user_profiles (user_id, bio, status) VALUES
(1, 1, 'Software engineer passionate about web development and open source', 'active'),
(2, 2, 'Digital marketing specialist with expertise in SEO and content strategy', 'active'),
(3, 3, 'Product manager focused on user experience and innovation', 'active'),
(4, 4, 'Data analyst with skills in data visualization and business intelligence', 'active'),
(5, 5, 'UI/UX designer creating intuitive and beautiful interfaces', 'active'),
(6, 6, 'Full stack developer experienced in Node.js and React', 'active'),
(7, 7, 'DevOps engineer specializing in cloud infrastructure and CI/CD', 'active'),
(8, 8, 'Content writer and technical documentation specialist', 'active'),
(9, 9, 'Quality assurance engineer focused on automated testing', 'active'),
(10, 10, 'Business analyst bridging the gap between IT and business', 'active'),
(11, 11, 'Database administrator with expertise in MySQL and PostgreSQL', 'active'),
(12, 12, 'Frontend developer specializing in Vue.js and TypeScript', 'active'),
(13, 13, 'Backend engineer focused on microservices architecture', 'active'),
(14, 14, 'Security specialist in cybersecurity and penetration testing', 'active'),
(15, 15, 'Machine learning engineer with expertise in deep learning', 'active'),
(16, 16, 'Project manager experienced in agile and scrum methodologies', 'active'),
(17, 17, 'Systems administrator managing enterprise infrastructure', 'active'),
(18, 18, 'Mobile developer creating iOS and Android applications', 'active'),
(19, 19, 'Solutions architect designing scalable enterprise systems', 'active'),
(20, 20, 'Technical lead mentoring junior developers and code review', 'active'),
(21, 21, 'Cloud architect expertise in AWS and Azure deployment', 'active'),
(22, 22, 'API developer creating RESTful and GraphQL services', 'active'),
(23, 23, 'Performance optimization specialist for web applications', 'active'),
(24, 24, 'Blockchain developer specializing in smart contracts', 'active'),
(25, 25, 'Data scientist focused on predictive analytics and modeling', 'active'),
(26, 26, 'Integration specialist connecting enterprise systems', 'active'),
(27, 27, 'Release manager overseeing software deployment pipelines', 'active'),
(28, 28, 'Support engineer providing technical customer assistance', 'active'),
(29, 29, 'Compliance officer ensuring regulatory standards adherence', 'active'),
(30, 30, 'Training specialist developing educational materials and courses', 'active');
